Repository CMU-313/nodebb-f24-team-team, pull requests merged in 2024-10, with the labels that each got.

#50 Adds automated testing for anonymous post display
  dump.rdb
  src/topics/index.js
  test/posts/anonymous.js
Labels: enhancement

#51 Add check so that people can’t register with "anonymous" in their username
  dump.rdb
  public/src/utils.common.js
  test/controllers-admin.js
  test/posts/anonymous.js
Labels: enhancement

#52 Update UserGuide.md
  UserGuide.md
Labels: documentation

#54 UserGuide update
  UserGuide.md
Labels: documentation

#53 Add deanonymize button to frontend and setup backend for future
  public/src/client/topic/change-owner.js
  src/views/modals/change-owner.tpl
Labels: enhancement

#68 Fix Azure deployment failure
  .github/workflows/azure-deploy-f24.yml
  package.json
Labels: bug
